# Generated by Django 3.2.9 on 2022-01-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('attendedLectures', models.IntegerField(default=0)),
                ('totalLectures', models.IntegerField(default=0)),
            ],
        ),
    ]
